name: QGIS Python Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .docker
    strategy:
      matrix:
        qgis_version: [
#          "latest",
#          "3.40",
          "release-3_34",
          "release-3_28",
        ]
    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Make env
        run: cd .. && make env QGIS_VERSION=${{ matrix.qgis_version }}

      - name: Launching docker compose
        run: ./start.sh

      - name: Running tests
        run: ./exec.sh
